[project]
name = "simplellama"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "ipdb>=0.13.13",
    "numpy>=2.3.1",
    "torch>=2.7.1",
]
