data:
  hf_data_path: "roneneldan/TinyStories"
  tokenizer_id: "HuggingFaceTB/SmolLM2-135M"
  seq_len: 4096
  data_path: "./data"
  train_data_path: "./data/train.bin"
  test_data_path: "./data/test.bin"

llama_config:
  d_model : 576
  intermediate_size : 1536
  vocab_size : 49152
  d_head : 64
  q_heads : 9
  num_layers : 15
  kv_heads : 3
  rms_norm_eps : 0.00001
  rope_theta : 50000
  causal: TRUE

optim:
  lr: 2e-4
  steps: 5000
  batch_size: 1
  grad_accum_steps: 128
  t_max: 5
  max_norm: 1
  adamw:
    eps: 1e-8
    beta1: 0.8
    beta2: 0.95
    weight_decay: 0.1

device: "cuda"
seed: 42
test_freq: 1000
